# Refreshes assets/registry-snapshot.js with data from registries that a web page
# can't query directly from the visitor's browser (EU CTIS blocks cross-site requests).
# Runs automatically every morning via .github/workflows/registry-snapshot.yml.
# To run by hand from the CureChecker folder:  powershell -ExecutionPolicy Bypass -File tools\update-registries.ps1
# Reads each disease's slug and `search` term from assets/diseases.js.

$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$enc = New-Object System.Text.UTF8Encoding($false)
$assets = Join-Path $root 'assets'   # works on Windows and on GitHub's Linux runners
$src = [IO.File]::ReadAllText((Join-Path $assets 'diseases.js'), $enc)

$diseases = [regex]::Matches($src, 'slug:\s*"([^"]+)"[\s\S]*?search:\s*"([^"]+)"') | ForEach-Object {
  [pscustomobject]@{ slug = $_.Groups[1].Value; search = $_.Groups[2].Value }
}

function Get-CtisTrials([string]$term) {
  $all = @(); $page = 1
  do {
    $body = @{ pagination = @{ page = $page; size = 100 }; sort = @{ property = 'decisionDate'; direction = 'DESC' }; searchCriteria = @{ containAll = $term } } | ConvertTo-Json -Depth 5
    $r = Invoke-RestMethod -Uri 'https://euclinicaltrials.eu/ctis-public-api/search' -Method Post -ContentType 'application/json' -Body $body -TimeoutSec 60
    $all += $r.data
    $page++
  } while ($r.pagination.nextPage -and $page -le 20)
  # CTIS full-text search is loose: keep trials whose conditions or title really are about the disease
  # (drops matches such as "non-cystic fibrosis bronchiectasis").
  $pattern = [regex]::Escape($term)
  $all | Where-Object {
    $text = ("$($_.conditions) $($_.ctTitle)") -replace "(?i)non[- ]$pattern", ''
    $text -match "(?i)$pattern"
  }
}

$out = [ordered]@{}
foreach ($d in $diseases) {
  Write-Host "CTIS: $($d.slug) ($($d.search))"
  try {
    $trials = @(Get-CtisTrials $d.search)
    $newest = $trials | Select-Object -First 6 | ForEach-Object {
      [ordered]@{
        id        = $_.ctNumber
        title     = $_.ctTitle
        sponsor   = $_.sponsor
        countries = (($_.trialCountries -split ',') | ForEach-Object { ($_ -split ':')[0].Trim() } | Where-Object { $_ }) -join ', '
        decided   = $_.decisionDateOverall
      }
    }
    $out[$d.slug] = [ordered]@{ ctis = [ordered]@{ total = $trials.Count; newest = @($newest) } }
  } catch {
    Write-Warning "CTIS failed for $($d.slug): $($_.Exception.Message)"
    $out[$d.slug] = [ordered]@{ ctis = $null }
  }
}

$json = [ordered]@{ generated = (Get-Date).ToString('yyyy-MM-dd'); diseases = $out } | ConvertTo-Json -Depth 8
$js = "// Generated by tools/update-registries.ps1. Do not edit by hand.`r`nwindow.CURECHECKER_REGISTRY = $json;`r`n"
[IO.File]::WriteAllText((Join-Path $assets 'registry-snapshot.js'), $js, $enc)
Write-Host "Wrote assets/registry-snapshot.js"
